name: The Grid Sucks
favicon: null
layout_spectrum: 0.33752839267253876
typography_spectrum: 0.6659928858280182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.639979133149609
  lightness: 0.33689627703279257
  saturation: 0.05146396718919277
  rhythmicContrast: 0.2879781925585121
purpose: []
